name: Latest blog posts workflow
on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README.md with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://bplociennik.pl/index.xml"
          max_post_count: 5
